function flag = check_pitot_correction(nas, measures, settings)
    
    flag =  settings.flagAscent && ...
            nas.flag.flag_pitot_correction && ...
            measures.pitot.lastindex ~= measures.pitot.index && ...
            measures.pitot.mach >= nas.PitotThreshold;

end
