function nasStates = run_NASII(sensorData, settings, environment)

%%% NAS II - INERTIAL PROPAGATOR %%% 
%
% ------------------------------------------------------------------------
%
% DESCRIPTION:
% Navigation and Attitude System (NAS), second iteration of the state estimation algorithm
% without sensor correction, using only inertial propagation via better IMU sensors.
%
%
% CONTRIBUTORS:
% Nicolò Corbo
%
% ------------------------------------------------------------------------
%
% Copyright © 2025, Skyward Experimental Rocketry, GNC IPT
%
% All rights reserved
% SPDX-License-Identifier: GPL-3.0-or-later
%
% ------------------------------------------------------------------------
% INPUTS:
%
% sensorData            = Struct containing the sensor data generated by the simulator
%
% settings              = Struct containing the settings of the algorithm
%
% environment           = Struct containing the environment data and parameters
% 
% OUTPUTS:
%
% nasStates             = Vector containing the states estimated by the NAS II algorithm:
%                        - NED Acceleration
%                        - Body Acceleration
%                        - NED Velocity
%                        - NED Position
%                        - Angular Velocity
%                        - Quaternion
% ------------------------------------------------------------------------

%% Propagation of the states 



