%{
export configuration files for NAS algorithm (for our friends of software development)
%}

folder = "ConfigData/NASConfig";
if ~exist(ConDataPath+"/"+folder,"dir")
    mkdir(ConDataPath+"/"+folder)
end

% first file: configuration parameters
configNAS_export_table = table;
configValues = [settings.frequencies.NASFrequency, ...
    settings.nas.sigma_beta, settings.nas.sigma_w, settings.nas.sigma_acc, ...
    settings.nas.sigma_mag, settings.nas.sigma_GPS(1,1),settings.nas.sigma_GPS(3,3), ...
    settings.nas.sigma_baro, sqrt(settings.nas.QLinear(1,1)),sqrt(settings.nas.QLinear(4,4)), ...
    settings.nas.sigma_pitot_static, settings.nas.sigma_pitot_dynamic, ...
    settings.nas.P(1,1), settings.nas.P(3,3), settings.nas.P(4,4), settings.nas.P(6,6), ...
    settings.nas.P(7,7), settings.nas.P(10,10), ...
    settings.nas.ned_mag(1), settings.nas.ned_mag(2), settings.nas.ned_mag(3), ...
    settings.nas.mag_decimate, 34, ...
    settings.nas.acc1g_confidence,settings.nas.acc1g_samples, ...
    settings.nas.PitotThreshold, settings.nas.GPS.a, settings.nas.GPS.b, ...
    settings.nas.baro.a, settings.nas.baro.n];

configNASvarNames = {'NAS_FREQUENCY',...
    'SIGMA_BETA', 'SIGMA_W', 'SIGMA_ACC', ...
    'SIGMA_MAG', 'SIGMA_GPS_POS', 'SIGMA_GPS_VEL', ...
    'SIGMA_BAR', 'SIGMA_POS', 'SIGMA_VEL', ...
    'SIGMA_PITOT_STATIC', 'SIGMA_PITOT_DYNAMIC', ...
    'P_POS', 'P_POS_VERTICAL', 'P_VEL', 'P_VEL_VERTICAL', ...
    'P_ATT', 'P_BIAS', ...
    'NED_MAG_N', 'NED_MAG_E', 'NED_MAG_D', ...
    'MAGNETOMETER_DECIMATE', 'DISABLE_GPS_ACCELERATION', ...
    'ACCELERATION_1G_CONFIDENCE', 'ACCELERATION_1G_SAMPLES', ...
    'PITOT_MACH_THRESHOLD', 'GPS_lat_const','GPS_lon_const',...
    'BARO_T_COEFF','BARO_P_COEFF'};
for i = 1:size(configValues,2)
    configNAS_export_table(1,i) = table(configValues(1,i));
end
configNAS_export_table.Properties.VariableNames = configNASvarNames;
writetable(configNAS_export_table,ConDataPath+"/"+folder+"/NAS_configs_data.csv")
