%{

extract only useful parameters from MSA toolkit:

%}

fieldsToRemove = {'x_final','y_final', ...
                  'boatL', 'boatD', ...
                  'Vx_final','Vy_final', ...
                  'Local', ...
                  'lpin', 'lrampa', ...
                  'pitotConeLength','pitotDiameter','pitotLength', ...
                  'mNoMot', ...
                  'pMod','cMod', ...
                  'limLat','limLon',...
                  };

rmfield(settings, fieldsToRemove);
